# Change these first
owner: HDVinnie # Your GitHub organization or username, where this repository lives
repo: TrackerHub # The name of this repository

sites:
  - name: Aither
    url: $AIH
    icon: $AIH_ICON
    maxResponseTime: 1000
  - name: AlphaRatio
    url: $AR
    icon: $AR_ICON
    maxResponseTime: 1000
  - name: AnimeBytes
    url: $AB
    icon: $AB_ICON
    maxResponseTime: 1000
  - name: Anthelion
    url: $ATH
    icon: $ATH_ICON
    maxResponseTime: 1000
  - name: AsianCinema
    url: $ACM
    icon: $ACM_ICON
    maxResponseTime: 1000
  - name: BeyondHD
    url: $BHD
    icon: $BHD_ICON
    maxResponseTime: 1000
  - name: Bibliotik
    url: $BIB
    icon: $BIB_ICON
    maxResponseTime: 1000
  - name: Blutopia
    url: $BLU
    icon: $BLU_ICON
    maxResponseTime: 1000
  - name: BroadcasTheNet
    url: $BTN
    icon: $BTN_ICON
    maxResponseTime: 1000
  - name: DesiTorrents
    url: $DST
    icon: $DST_ICON
    maxResponseTime: 1000
  - name: Empornium
    url: $EMP
    icon: $EMP_ICON
    maxResponseTime: 1000
  - name: Exoticaz
    url: $EZ
    icon: $EZ_ICON
    maxResponseTime: 1000
  - name: FearNoPeer
    url: $FNP
    icon: $FNP_ICON
    maxResponseTime: 1000
  - name: GazelleGames
    url: $GGN
    icon: $GGN_ICON
    maxResponseTime: 1000
  - name: GreatPosterWall
    url: $GPW
    icon: $GPW_ICON
    maxResponseTime: 1000
  - name: HawkeUno
    url: $UNO
    icon: $UNO_ICON
    maxResponseTime: 1000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: HDBits
    url: $HDB
    icon: $HDB_ICON
    maxResponseTime: 1000
  - name: MorethanTV
    url: $MTV
    icon: $MTV_ICON
    maxResponseTime: 1000
  - name: MyAnonaMouse
    url: $MAM
    icon: $MAM_ICON
    maxResponseTime: 1000
  - name: Nebulance
    url: $NBL
    icon: $NBL_ICON
    maxResponseTime: 1000
  - name: OnlyEncodes
    url: $OE
    icon: $OE_ICON
    maxResponseTime: 1000
  - name: Orpheus
    url: $OPS
    icon: $OPS_ICON
    maxResponseTime: 1000
  - name: PrivateHD
    url: $PHD
    icon: $PHD_ICON
    maxResponseTime: 1000
  - name: PassThePopcorn
    url: $PTP
    icon: $PTP_ICON
    maxResponseTime: 1000
  - name: Redacted
    url: $RED
    icon: $RED_ICON
    maxResponseTime: 1000
  - name: SceneTime
    url: $ST
    icon: $ST_ICON
    maxResponseTime: 1000
  - name: Secret-Cinema
    url: $SC
    icon: $SC_ICON
    maxResponseTime: 1000
  - name: TorrentLeech
    url: $TL
    icon: $TL_ICON
    maxResponseTime: 1000
  - name: UHDBits
    url: $UHD
    icon: $UHD_ICON
    maxResponseTime: 1000

status-website:
  workflowSchedule:
    uptime: "*/5 * * * *"
  baseUrl: /TrackerHub
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TrackerHub
  theme: night
  introTitle: "**TrackerHub** is the open-source uptime monitor and status page for trackers, powered entirely by GitHub for free."
  introMessage: Maintained with 💖 by HDVinnie
  navbar:
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
    - title: Tracker Spreadsheet
      href: https://hdvinnie.github.io/Private-Trackers-Spreadsheet
