# Change these first
owner: HDVinnie # Your GitHub organization or username, where this repository lives
repo: TrackerHub # The name of this repository

sites:
  - name: Aither
    url: $AIH
    icon: $AIH_ICON
    maxResponseTime: 500
  - name: AlphaRatio
    url: $AR
    icon: $AR_ICON
    maxResponseTime: 500
  - name: BeyondHD
    url: $BHD
    icon: $BHD_ICON
    maxResponseTime: 500
  - name: Bibliotik
    url: $BIB
    icon: $BIB_ICON
    maxResponseTime: 500
  - name: Blutopia
    url: $BLU
    icon: $BLU_ICON
    maxResponseTime: 500
    assignees:
      - HDVinnie
  - name: BroadcasTheNet
    url: $BTN
    icon: $BTN_ICON
    maxResponseTime: 500
  - name: DesiTorrents
    url: $DST
    icon: $DST_ICON
    maxResponseTime: 500
  - name: Empornium
    url: $EMP
    icon: $EMP_ICON
    maxResponseTime: 500
  - name: GazelleGames
    url: $GGN
    icon: $GGN_ICON
    maxResponseTime: 500
  - name: GreatPosterWall
    url: $GPW
    icon: $GPW_ICON
    maxResponseTime: 500
  - name: HDBits
    url: $HDB
    icon: $HDB_ICON
    maxResponseTime: 500
  - name: MorethanTV
    url: $MTV
    icon: $MTV_ICON
    maxResponseTime: 500
  - name: MyAnonaMouse
    url: $MAM
    icon: $MAM_ICON
    maxResponseTime: 500
  - name: Orpheus
    url: $OPS
    icon: $OPS_ICON
    maxResponseTime: 500
  - name: PrivateHD
    url: $PHD
    icon: $PHD_ICON
    maxResponseTime: 500
  - name: PassThePopcorn
    url: $PTP
    icon: $PTP_ICON
    maxResponseTime: 500
  - name: Redacted
    url: $RED
    icon: $RED_ICON
    maxResponseTime: 500
  - name: Telly
    url: $TLY
    icon: $TLY_ICON
    maxResponseTime: 500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /TrackerHub
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TrackerHub
  theme: night
  introTitle: "**TrackerHub** is the open-source uptime monitor and status page for trackers, powered entirely by GitHub for free."
  introMessage: Maintained with 💖 by HDVinnie
  navbar:
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
    - title: Tracker Spreadsheet
      href: https://hdvinnie.github.io/Private-Trackers-Spreadsheet

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
