# Change these first
owner: HDVinnie # Your GitHub organization or username, where this repository lives
repo: TrackerHub # The name of this repository

sites:
  - name: BHD
    url: $BHD
    icon: $BHD_ICON
  - name: BLU
    url: $BLU
    icon: $BLU_ICON
  - name: BTN
    url: $BTN
    icon: $BTN_ICON
  - name: BTN Announce
    url: $BTN_ANNOUNCE
  - name: HDB
    url: $HDB
    icon: $HDB_ICON
  - name: PTP
    url: $PTP
    icon: $PTP_ICON
  - name: PTP Announce
    url: $PTP_ANNOUNCE
  - name: RED
    url: $RED
    icon: $RED_ICON
  - name: RED Announce
    url: $RED_ANNOUNCE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /TrackerHub
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TrackerHub
  theme: night
  introTitle: "**TrackerHub** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: Powered By GitHub
  navbar:
    - title: Status
      href: /
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
    - title: Tracker Spreadsheet
      href: https://hdvinnie.github.io/Private-Trackers-Spreadsheet

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
