# Change these first
owner: HDVinnie # Your GitHub organization or username, where this repository lives
repo: TrackerHub # The name of this repository

sites:
  - name: BeyondHD
    url: $BHD
    icon: $BHD_ICON
  - name: Blutopia
    url: $BLU
    icon: $BLU_ICON
  - name: BroadcasTheNet
    url: $BTN
    icon: $BTN_ICON
  - name: BroadcasTheNet Announce
    url: $BTN_ANNOUNCE
  - name: HDBits
    url: $HDB
    icon: $HDB_ICON
  - name: PrivateHD
    url: $PHD
    icon: $PHD_ICON
  - name: PrivateHD Announce
    url: $PHD_ANNOUNCE
  - name: PassThePopcorn
    url: $PTP
    icon: $PTP_ICON
  - name: PassThePopcorn Announce
    url: $PTP_ANNOUNCE
  - name: Redacted
    url: $RED
    icon: $RED_ICON
  - name: Redacted Announce
    url: $RED_ANNOUNCE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /TrackerHub
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TrackerHub
  theme: night
  introTitle: "**TrackerHub** is the open-source uptime monitor and status page for trackers, powered entirely by GitHub."
  introMessage: Maintained with 💖 by HDVinnie
  navbar:
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
    - title: Tracker Spreadsheet
      href: https://hdvinnie.github.io/Private-Trackers-Spreadsheet

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
